# The Console CRD is for the top level (cluster scoped) Console config
# The API for this exists in openshift/api/config/v1/types_console.go
# This is the intended user facing console configuration.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: console.config.openshift.io
spec:
  scope: Cluster
  group: config.openshift.io
  names:
    kind: Console
    listKind: ConsoleList
    plural: consoles
    singular: console
  subresources:
    status: {}
