kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
  namespace: openshift-console
roleRef:
  kind: Role
  name: console-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: console-operator
  namespace: openshift-console-operator
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
  namespace: openshift-console-operator
roleRef:
  kind: Role
  name: console-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: console-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console-operator
subjects:
- kind: ServiceAccount
  name: console-operator
  namespace: openshift-console-operator
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
  namespace: openshift-config-managed
roleRef:
  kind: Role
  name: console-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: console-operator
    namespace: openshift-console-operator
