apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: console
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
    - name: openshift-console
      version: "0.0.1-snapshot_openshift"
