apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devconsoles.operator.openshift.io
spec:
  scope: Namespace
  group: operator.openshift.io
  names:
    kind: Devconsole
    listKind: DevconsoleList
    plural: devconsoles
    singular: devconsole
  subresources:
    status: {}
  versions:
    - name: v1
      served: true
      storage: true
