apiVersion: "console.openshift.io/v1alpha1"
kind: "Console"
metadata:
  # do not change the name, this is required to match within the operator
  name: "openshift-console"
  # namespace: openshift-console
  # for dev:
  namespace: openshift-console-operator-test
spec:
  paused: false
  # what needs to be customized here?
  # fewest knobs possible!
  # this will need to be reflected in the
  # pkg/apis/console/v1alpha1/types.go file
  # count is # of replicas
  count: 1
  # this is the console image
  baseImage: quay.io/openshift/origin-console
  # note: version with a @sha does not work, @ is not valid starting a string in yaml
  # version:
  # location of the master should NOT be needed, the console should automatically use
  # the service for the cluster API w/o us having to declare anything
  # masterPublicURL:
  # the log level for the operator itself.
  # note: should there be a lvl for the components as well?
  logging:
    level: 0